CREATE TABLE roles
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_removed BOOLEAN                                  NOT NULL,
    name       VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_removed BOOLEAN                                  NOT NULL,
    login      VARCHAR(255)                             NOT NULL,
    password   VARCHAR(255)                             NOT NULL,
    first_name VARCHAR(255)                             NOT NULL,
    last_name  VARCHAR(255)                             NOT NULL,
    sur_name   VARCHAR(255)                             NOT NULL,
    email      VARCHAR(255)                             NOT NULL,
    last_visit TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user_role FOREIGN KEY (role_id) REFERENCES roles (id);

---------------------------------------------Aircraft-----------------------------------------------

CREATE TABLE aircraft

(
    id            INTEGER      NOT NULL,
    serial_number INTEGER      NOT NULL,
    reg_number    VARCHAR(255) NOT NULL,
    description   VARCHAR(255),
    model         VARCHAR(255),
    is_operating  BOOLEAN      NOT NULL,
    CONSTRAINT pk_aircraft PRIMARY KEY (id)
);
---------------------------------------------Flight-----------------------------------------------

CREATE TABLE flight
(
    id            INTEGER NOT NULL,
    duration      INTEGER NOT NULL,
    rate_per_hour FLOAT,
    date          TIMESTAMP WITHOUT TIME ZONE,
    aircraft_id   INTEGER,
    CONSTRAINT pk_flight PRIMARY KEY (id)
);

ALTER TABLE flight
    ADD CONSTRAINT FK_FLIGHT_ON_AIRCRAFT FOREIGN KEY (aircraft_id) REFERENCES aircraft (id);

---------------------------------------------Component-----------------------------------------------

CREATE TABLE component
(
    id               INTEGER      NOT NULL,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(255),
    price            DECIMAL      NOT NULL,
    status           BOOLEAN      NOT NULL,
    life_time        INTEGER      NOT NULL,
    manufacture_date TIMESTAMP WITHOUT TIME ZONE,
    aircraft_id      INTEGER,
    warehouse        INTEGER,
    CONSTRAINT pk_component PRIMARY KEY (id)
);

ALTER TABLE component
    ADD CONSTRAINT FK_COMPONENT_ON_AIRCRAFT FOREIGN KEY (aircraft_id) REFERENCES aircraft (id);



---------------------------------------------Warehouse-----------------------------------------------

CREATE TABLE warehouse
(
    id       INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT pk_warehouse PRIMARY KEY (id)
);

ALTER TABLE warehouse
    ADD CONSTRAINT FK_WAREHOUSE_ON_COMPONENT FOREIGN KEY (component_id) REFERENCES component (id);


---------------------------------------------Work Card-----------------------------------------------

CREATE TABLE work_card
(
    id               INTEGER                     NOT NULL,
    planned_date     TIMESTAMP WITHOUT TIME ZONE,
    replacement_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status           BOOLEAN                     NOT NULL,
    aircraft_id      INTEGER,
    component_id     INTEGER,
    CONSTRAINT pk_workcard PRIMARY KEY (id)
);

ALTER TABLE work_card
    ADD CONSTRAINT FK_WORKCARD_ON_AIRCRAFT FOREIGN KEY (aircraft_id) REFERENCES aircraft (id);

ALTER TABLE work_card
    ADD CONSTRAINT FK_WORKCARD_ON_COMPONENT FOREIGN KEY (component_id) REFERENCES component (id);

---------------------------------------------Balance-----------------------------------------------

CREATE TABLE balance

(
    id           INTEGER NOT NULL,
    balance      DECIMAL,
    flight_id    INTEGER,
    component_id INTEGER,
    CONSTRAINT pk_balance PRIMARY KEY (id)
);

ALTER TABLE balance
    ADD CONSTRAINT FK_BALANCE_ON_COMPONENT FOREIGN KEY (component_id) REFERENCES component (id);

ALTER TABLE balance
    ADD CONSTRAINT FK_BALANCE_ON_FLIGHT FOREIGN KEY (flight_id) REFERENCES flight (id);