###
POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json

{
  "login": "aston",
  "password": "password123",
  "userRole": {
    "name": "ROLE_USER"
  },
  "firstName": "John",
  "lastName": "Doe",
  "surName": "Smith",
  "email": "johndoe@example.com",
  "last_visit": "2012-04-23T18:25:43.511Z"
}


###
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "login": "aston",
  "password": "password123"
}
