--liquibase formatted sql

--changeset liquibase:1
CREATE TABLE aircraft
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    serial_number INTEGER                                  NOT NULL,
    reg_number    VARCHAR(255)                             NOT NULL,
    description   VARCHAR(255),
    model         VARCHAR(255),
    is_operating  BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_aircraft PRIMARY KEY (id)
);

--changeset liquibase:2
INSERT INTO aircraft (serial_number, reg_number, description, model, is_operating)
VALUES (897563, 'VQ-BNM', 'in DemoAirlines possession', 'Boeing 737-NG', true),
       (897532, 'VP-BMS', 'in TestAirlines possession', 'Boeing 747', true)