--liquibase formatted sql

--changeset liquibase:3
CREATE TABLE balance
(
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance                 DECIMAL,
    CONSTRAINT pk_balance   PRIMARY KEY (id)
);

--changeset liquibase:4
INSERT INTO balance(balance) VALUES (1500000)