--liquibase formatted sql

--changeset liquibase:8
CREATE TABLE component_order
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    component_quantity  INTEGER                                  NOT NULL,
    component_id        INTEGER,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

--changeset liquibase:9
ALTER TABLE component_order
    ADD CONSTRAINT FK_ORDER_ON_COMPONENT FOREIGN KEY (component_id) REFERENCES component (id);

--changeset liquibase:10
INSERT INTO component_order (component_quantity, component_id)
VALUES (12,1),
       (4,2),
       (5,3),
       (6,4),
       (1,5),
       (2,6)
