--liquibase formatted sql

--changeset liquibase:5
CREATE TABLE component
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                             NOT NULL,
    description      VARCHAR(255),
    price            DECIMAL                                  NOT NULL,
    is_installed     BOOLEAN,
    life_time        INTEGER                                  NOT NULL,
    manufacture_date TIMESTAMP WITHOUT TIME ZONE,
    aircraft_id      INTEGER,
    CONSTRAINT pk_component PRIMARY KEY (id)
);

--changeset liquibase:6
ALTER TABLE component
    ADD CONSTRAINT FK_COMPONENT_ON_AIRCRAFT FOREIGN KEY (aircraft_id) REFERENCES aircraft (id);

--changeset liquibase:7
INSERT INTO component (name, description, price, is_installed, life_time, manufacture_date, aircraft_id)
VALUES ('Escape Slide', 'ATA 25 - Emergency Equipment', 12500, false, 5, '2020-05-11', 1),
       ('Oxygen Cylinder', 'ATA 35 - Oxygen', 7500, false, 3, '2022-04-12', 1),
       ('Main Battery', 'ATA 24 - Electricity', 1000, false, 1, '2023-04-11', 1),
       ('Fire Extinguisher', 'ATA 26 - Fire Protection', 8000, false, 5, '2021-12-29', 2),
       ('Landing Gear', 'ATA 32 - Landing Gear', 75000, false, 10, '2015-01-12', 2),
       ('APU', 'ATA 49 - AUXILIARY POWER UNIT', 250000, false, 10, '2017-12-21', 2)
