--liquibase formatted sql

--changeset liquibase:11
CREATE TABLE flight
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    duration      INTEGER                                  NOT NULL,
    rate_per_hour FLOAT,
    flight_date   TIMESTAMP WITHOUT TIME ZONE,
    aircraft_id   INTEGER                                  NOT NULL,
    CONSTRAINT pk_flight PRIMARY KEY (id)
);

--changeset liquibase:12
ALTER TABLE flight
    ADD CONSTRAINT FK_FLIGHT_ON_AIRCRAFT FOREIGN KEY (aircraft_id) REFERENCES aircraft (id);

--changeset liquibase:13
INSERT INTO flight (duration, rate_per_hour, flight_date, aircraft_id)
VALUES (7, 1200, '2015-05-11', 1),
       (12, 1000, '2015-04-15', 1),
       (2, 1500, '2015-03-12', 2)