--liquibase formatted sql

--changeset liquibase:16
CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_removed BOOLEAN                                  NOT NULL,
    login      VARCHAR(255)                             NOT NULL,
    password   VARCHAR(255)                             NOT NULL,
    first_name VARCHAR(255)                             NOT NULL,
    last_name  VARCHAR(255)                             NOT NULL,
    sur_name   VARCHAR(255)                             NOT NULL,
    email      VARCHAR(255)                             NOT NULL,
    last_visit TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

--changeset liquibase:17
INSERT INTO users (is_removed, login, password, first_name, last_name, sur_name, email, last_visit)
VALUES (false, 'admin', 'admin', 'Rustam', 'Arturovich', 'Bikiteev', 'rb@gmail.com', '2023-05-29'),
       (false, 'root', 'root', 'Ivan', 'Ivanovich', 'Ivanov', 'ivan@gmail.com', '2023-05-28'),
       (false, 'demo', 'demo', 'Igor', 'Igorevich', 'Igorev', 'igor@gmail.com', '2023-05-27')