--liquibase formatted sql

--changeset liquibase:22
CREATE TABLE warehouse
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity     INTEGER,
    component_id INTEGER,
    CONSTRAINT pk_warehouse PRIMARY KEY (id)
);

--changeset liquibase:23
ALTER TABLE warehouse
    ADD CONSTRAINT FK_WAREHOUSE_ON_COMPONENT FOREIGN KEY (component_id) REFERENCES component (id);

--changeset liquibase:24
INSERT INTO warehouse (quantity, component_id)
VALUES (8, 1),
       (7, 2),
       (16, 3),
       (5, 4),
       (3, 5),
       (2, 6)